Test
kafnyi/school pull request #21
Opened 2022-06-27 19:42 UTC by kafnyi

2022-06-28 09:01 UTC, ZaitzeV16 commented
Ezért tudsz merge-ölni...
"Repository owners and administrators can merge a pull request even if it hasn't received an approving review, or if a reviewer who requested changes has left the organization or is unavailable."

2022-06-28 09:09 UTC, ZaitzeV16 requested changes

2022-06-28 09:09 UTC, ZaitzeV16 commented on src/main/java/hu/wurfel/refference/school/diary/DiaryService.java
> +
```suggestion
```

2022-06-28 09:09 UTC, ZaitzeV16 commented on src/main/java/hu/wurfel/refference/school/diary/DiaryController.java
>  		return ResponseEntity.ok(answer);
```suggestion
		return ResponseEntity.ok(diaryService.getSearchResponseList(searchWith, searchBy, value));
```

2022-06-28 09:09 UTC, ZaitzeV16 commented on src/main/java/hu/wurfel/refference/school/diary/DiaryController.java
>  		List<Diary> answer;
```suggestion
```

2022-06-28 09:09 UTC, ZaitzeV16 commented on src/main/java/hu/wurfel/refference/school/division/ClassController.java
>          return ResponseEntity.ok(answer);
```suggestion
        return ResponseEntity.ok(classService.getSearchResponseList(searchWith, searchBy, value));
```

2022-06-28 09:09 UTC, ZaitzeV16 commented on src/main/java/hu/wurfel/refference/school/division/ClassService.java
> +                return null;
Ez nyilván a többire is igaz. Ha nem akarod átalakítani, mert hogy switch-case és úgyis refactorolva lesz, azt megértem és ezegyszer el is nézem. 😄

2022-06-28 09:09 UTC, ZaitzeV16 commented on src/main/java/hu/wurfel/refference/school/subject/SubjectService.java
> +
```suggestion
```

2022-06-28 09:09 UTC, ZaitzeV16 commented on src/main/java/hu/wurfel/refference/school/teacher/TeacherService.java
> +
```suggestion
```

2022-06-29 12:14 UTC, merged

2022-06-29 12:16 UTC, ZaitzeV16 commented
Amikor van githubon egy change suggestion, azt itt helyben el tudod fogadni és egyből commitolni.

2022-06-29 12:44 UTC, kafnyi commented
hmm... akkor ez egy kellemes tanulópénz... köszönöm azért